# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

dist: trusty
r:
  - oldrel
  - release
  - devel
latex: false

cache:
  packages: true
  directories:
    - $HOME/.cache/pip

before_install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - rm miniconda.sh
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n r-reticulate pip numpy

before_script:
  - source activate r-reticulate
  - ls
  - set -a
  - source R/version.R
  - set +a
  - if [ "$PM4PY_DEVELOPMENT" == "TRUE" ]; then pip install -r $PM4PY_DEVELOPMENT_DEPENDENCIES; else echo "Skipping"; fi
  - pip install $PM4PY_PIP
