# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

dist: trusty
sudo: false

r: release
latex: false

cache:
  packages: true
  directories:
    - $HOME/.cache/pip

env:
  global:
   - RETICULATE_PYTHON="/usr/bin/python3"

before_script:
  - sudo apt-get update
  - sudo apt-get install python3-pip
  - pip3 install --upgrade --ignore-installed --user virtualenv
  - pip3 install --upgrade --ignore-installed --user numpy
  - R CMD INSTALL .
  - R -e 'reticulate::py_config();library(pm4py);pm4py::install_pm4py()'
