# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

dist: trusty
sudo: false

r: release
latex: false

cache:
  packages: true
  directories:
    - $HOME/.cache/pip

before_script:
  - sudo apt-get update
  - sudo apt-get install python3
  - pip install --upgrade --ignore-installed --user travis virtualenv
  - pip install --upgrade --ignore-installed --user travis numpy
  - R CMD INSTALL .
  - R -e 'use_python("/usr/bin/python3", required = TRUE)'
  - R -e 'pm4py::install_pm4py()'
