# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
before_install:
  - pip install numpy
  - pip install pm4py
r: release
cache: packages
latex: false
